# Generated by Django 5.1.4 on 2025-03-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemodel',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
