# Generated by Django 5.1.4 on 2025-03-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_notemodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemodel',
            name='tags',
        ),
    ]
